# Kaggle Python

In [1]:
spam_amount = 0
print(spam_amount)

# Ordering Spam, egg, Spam, Spam, bacon and Spam (4 more servings of Spam)
spam_amount = spam_amount + 4

if spam_amount > 0:
    print("But I don't want ANY spam!")

viking_song = "Spam " * spam_amount
print(viking_song)

0
But I don't want ANY spam!
Spam Spam Spam Spam 


In [2]:
print(spam_amount)

4


In [3]:
# Ordering Spam, egg, Spam, Spam, bacon and Spam (4 more servings of Spam)
spam_amount = spam_amount + 4

In [4]:
if spam_amount > 0:
    print("But I don't want ANY spam!")

viking_song = "Spam Spam Spam"
print(viking_song)

But I don't want ANY spam!
Spam Spam Spam


In [5]:
viking_song = "Spam " * spam_amount
print(viking_song)

Spam Spam Spam Spam Spam Spam Spam Spam 


In [6]:
spam_amount = 0
type(spam_amount)

int

In [7]:

#Complete the code below. In case it's helpful, here is the table of available arithmetic operations:

#Operator	Name	    Description
#a + b	Addition	    Sum of a and b
#a - b	Subtraction	    Difference of a and b
#a * b	Multiplication	Product of a and b
#a / b	True division	Quotient of a and b
#a // b	Floor division	Quotient of a and b, removing fractional parts
#a % b	Modulus	Integer remainder after division of a by b
#a ** b	Exponentiation	a raised to the power of b
#-a	    Negation	    The negative of a

In [8]:
type(19.95)

float

In [9]:
print(5 / 2)
print(6 / 2)

2.5
3.0


The // operator gives us a result that's rounded down to the next integer.

In [10]:
print(5 // 2)
print(6 // 2)

2
3


In [11]:
hat_height_cm = 25
my_height_cm = 190
# How tall am I, in meters, when wearing my hat?
total_height_meters = hat_height_cm + my_height_cm / 100
print("Height in meters =", total_height_meters)

Height in meters = 26.9


Builtin functions for working with numbers

min and max return the minimum and maximum of their arguments, respectively...

In [12]:
print(min(1, 2, 3))
print(max(1, 2, 3))

1
3


abs returns the absolute value of an argument:

In [13]:
print(abs(32))
print(abs(-32))

32
32


In addition to being the names of Python's two main numerical types, int and float can also be called as functions which convert their arguments to the corresponding type:

In [14]:
print(float(10))
print(int(3.33))
# They can even be called on strings!
print(int('807') + 1)

10.0
3
808


The help() function is possibly the most important Python function you can learn. If you can remember how to use help(), you hold the key to understanding most other functions.

Here is an example:

In [15]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [16]:
help(round(-2.01))

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |

In [17]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.
    
    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



**Defining functions**

Builtin functions are great, but we can only get so far with them before we need to start defining our own functions. Below is a simple example.

In [18]:
def least_difference(a, b, c):
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

In [19]:
least_difference(1, 10, 100)
    

9

In [20]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)



Python isn't smart enough to read my code and turn it into a nice English description. However, when I write a function, I can provide a description in what's called the docstring.

In [21]:
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    
    >>> least_difference(1, 5, -5)
    4
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

In [22]:
least_difference(1, 5, -5)

4

In [23]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)
    Return the smallest difference between any two numbers
    among a, b and c.
    
    >>> least_difference(1, 5, -5)
    4



In [24]:
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    min(diff1, diff2, diff3)
    
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7),
)

None None None


In [25]:
print(1, 2, 3, sep=' < ')

1 < 2 < 3


In [26]:
def greet(who="Colin"):
    print("Hello,", who)
    
greet()
greet(who="Kaggle")
# (In this case, we don't need to specify the name of the argument, because it's unambiguous.)
greet("world")
greet("sameer")

Hello, Colin
Hello, Kaggle
Hello, world
Hello, sameer


In [27]:
def mult_by_five(x):
    return 5 * x

def call(fn, arg):
    """Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1), 
    sep='\n', # '\n' is the newline character - it starts a new line
)

5
25


In [28]:
def mod_5(x):
    """Return the remainder of x after dividing by 5"""
    return x % 5

print(
    'Which number is biggest?',
    max(100, 51, 14),
    'Which number is the biggest modulo 5?',
    max(100, 51, 14, key=mod_5),
    sep='\n',
)

Which number is biggest?
100
Which number is the biggest modulo 5?
14


***Booleans***

Python has a type of variable called bool. It has two possible values: True and False.

In [29]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


In [30]:
def can_run_for_president(age):
    """Can someone of the given age run for president in the US?"""
    # The US Constitution says you must be at least 35 years old
    return age >= 35

print("Can a 19-year-old run for president?", can_run_for_president(19))
print("Can a 45-year-old run for president?", can_run_for_president(45))

Can a 19-year-old run for president? False
Can a 45-year-old run for president? True


In [31]:
3.0 == 3

True

In [32]:
'3' == 3

False

In [33]:
def can_run_for_president(age, is_natural_born_citizen):
    """Can someone of the given age and citizenship status run for president in the US?"""
    # The US Constitution says you must be a natural born citizen *and* at least 35 years old
    return is_natural_born_citizen and (age >= 35)

print(can_run_for_president(19, True))
print(can_run_for_president(55, False))
print(can_run_for_president(55, True))

False
False
True


In [34]:
def is_odd(n):
    return (n % 2) == 1

print("Is 100 odd?", is_odd(100))
print("Is -1 odd?", is_odd(-1))

Is 100 odd? False
Is -1 odd? True


In [35]:
True or True and False

True

**Conditionals**

Booleans are most useful when combined with conditional statements, using the keywords if, elif, and else.

Conditional statements, often referred to as if-then statements, let you control what pieces of code are run based on the value of some Boolean condition. Here's an example:

In [36]:
def inspect(x):
    if x == 0:
        print(x, "is zero")
    elif x > 0:
        print(x, "is positive")
    elif x < 0:
        print(x, "is negative")
    else:
        print(x, "is unlike anything I've ever seen...")
inspect(0)
inspect(-15)


0 is zero
-15 is negative


In [37]:
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
    print("Always printed, regardless of x's value; x =", x)
f(1)
f(0)

Only printed when x is positive; x = 1
Also only printed when x is positive; x = 1
Always printed, regardless of x's value; x = 1
Always printed, regardless of x's value; x = 0


In [38]:
print(bool(1)) # all numbers are treated as true, except 0
print(bool(0))
print(bool("asf")) # all strings are treated as true, except the empty string ""
print(bool(""))

True
False
True
False


**Lists**

Lists in Python represent ordered sequences of values. Here is an example of how to create them:

In [39]:
primes = [2, 3, 5, 7]

In [40]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [41]:
planets[0]

'Mercury'

In [42]:
planets[-1]

'Neptune'

In [43]:
planets[0:3]

['Mercury', 'Venus', 'Earth']

In [44]:
planets[3:]

['Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [45]:
planets[1:-1]

['Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus']

In [46]:
planets[3] = 'Malacandra'
planets

['Mercury',
 'Venus',
 'Earth',
 'Malacandra',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune']

In [47]:
planets[:3] = ['Mur', 'Vee', 'Ur']
print(planets)
# That was silly. Let's give them back their old names
planets[:4] = ['Mercury', 'Venus', 'Earth', 'Mars',]

['Mur', 'Vee', 'Ur', 'Malacandra', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


In [48]:
len(planets)#len gives the length of a list:

8

In [49]:
# The planets sorted in alphabetical order
sorted(planets)

['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']

In [50]:
primes = [2, 3, 5, 7]
sum(primes)

17

In [51]:
max(primes)

7

In [52]:
x = 12
# x is a real number, so its imaginary part is 0.
print(x.imag)
# Here's how to make a complex number, in case you've ever been curious:
c = 12 + 3j
print(c.imag)

0
3.0


In [53]:
x.bit_length

<function int.bit_length()>

In [54]:
#list.append modifies a list by adding an item to the end:

# Pluto is a planet darn it!
planets.append('Pluto')

In [55]:
help(planets.append)

Help on built-in function append:

append(object, /) method of builtins.list instance
    Append object to the end of the list.



In [56]:
planets

['Mercury',
 'Venus',
 'Earth',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Pluto']

In [57]:
#list.pop removes and returns the last element of a list:

planets.pop()
planets

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [58]:
planets.index('Earth')


2

In [59]:
"Earth" in planets

True

In [60]:
t = (1, 2, 3)

In [61]:
x = 0.125
x.as_integer_ratio()#ratio

(1, 8)

In [62]:
numerator, denominator = x.as_integer_ratio()
print(numerator / denominator)

0.125


In [63]:
for planet in planets:
    print(planet, end=' ')

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [64]:
multiplicands = (2, 2, 2, 3, 3, 5,6)
product = 1
for mult in multiplicands:
    product = product * mult
product

2160

In [65]:
i = 0
while i < 10:
    print(i, end=' ')
    i += 1 # increase the value of i by 1

0 1 2 3 4 5 6 7 8 9 

In [66]:
squares = [n**2 for n in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [67]:
squares = []
for n in range(10):
    squares.append(n**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [68]:
short_planets = [planet for planet in planets if len(planet) < 6]
short_planets

['Venus', 'Earth', 'Mars']

In [69]:
loud_short_planets = [planet.upper() + '!' for planet in planets if len(planet) < 6]
loud_short_planets

['VENUS!', 'EARTH!', 'MARS!']

In [70]:
def count_negatives(nums):
    """
    Return the number of negative numbers in the given list.
    
    >>> count_negatives([5, -1, -2, 0, 3])
    2
    """
    n_negative = 0
    for num in nums:
        if num < 0:
            n_negative = n_negative + 1
    return n_negative

In [71]:
x = 'Pluto is a planet'
y = "Pluto is a planet"
x == y

True

#What you type...	What you get	example	                 print(example)
#\'	                '	           'What\'s up?'	         What's up?
#\"	                "	           "That's \"cool\""	     That's "cool"
#\\	                \	           "Look, a mountain: /\\"	 Look, a mountain: /\
#\n	                               "1\n 2 3"	                1 2 3

In [72]:
hello = "hello\nworld"
print(hello)

hello
world


In [73]:
print("hello")
print("world")
print("hello", end='')
print("pluto", end='')

hello
world
hellopluto

In [74]:
planet = 'Pluto'
planet[0]

'P'

In [75]:
planet[-3:]

'uto'

In [76]:
len(planet)

5

In [77]:
[char+'! ' for char in planet]

['P! ', 'l! ', 'u! ', 't! ', 'o! ']

In [2]:
claim = "Pluto is a planet!"
claim.upper()

'PLUTO IS A PLANET!'

In [79]:
claim.lower()

'pluto is a planet!'

In [80]:
claim.index('plan')

11

In [5]:
words = claim.split()
words

['Pluto', 'is', 'a', 'planet!']

In [1]:
datestr = '1956-01-31'
year, month, day = datestr.split('-')

In [83]:
'/'.join([month, day, year])

'01/31/1956'

In [84]:
planet + ", you'll always be the " + str(1) + "th planet to me."

"Pluto, you'll always be the 1th planet to me."

In [85]:
"{}, you'll always be the {}th planet to me.".format(planet, 8)

"Pluto, you'll always be the 8th planet to me."

In [86]:
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390
#         2 decimal points   3 decimal points, format as percent     separate with commas
"{} weighs about {:.2} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(
    planet, pluto_mass, pluto_mass / earth_mass, population,
)

"Pluto weighs about 1.3e+22 kilograms (0.218% of Earth's mass). It is home to 52,910,390 Plutonians."

In [87]:
s = """Pluto's a {0}.
No, it's a {1}.
{0}!
{1}!""".format('planet', 'dwarf planet')
print(s)

Pluto's a planet.
No, it's a dwarf planet.
planet!
dwarf planet!


In [88]:
numbers = {'one':1, 'two':2, 'three':3}

In [89]:
numbers['one']

1

In [90]:
numbers['eleven'] = 11
numbers

{'one': 1, 'two': 2, 'three': 3, 'eleven': 11}

In [91]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_to_initial = {planet: planet[0] for planet in planets}
planet_to_initial

{'Mercury': 'M',
 'Venus': 'V',
 'Earth': 'E',
 'Mars': 'M',
 'Jupiter': 'J',
 'Saturn': 'S',
 'Uranus': 'U',
 'Neptune': 'N'}

In [92]:
for k in numbers:
    print("{} = {}".format(k, numbers[k]))

one = 1
two = 2
three = 3
eleven = 11


In [93]:
' '.join(sorted(planet_to_initial.values()))

'E J M M N S U V'

In [94]:
for planet, initial in planet_to_initial.items():
    print("{} begins with \"{}\"".format(planet.rjust(10), initial))

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
   Jupiter begins with "J"
    Saturn begins with "S"
    Uranus begins with "U"
   Neptune begins with "N"


In [95]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [96]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [97]:
math.log(32, 2)

5.0

In [98]:
import math as mt
mt.pi

3.141592653589793

In [99]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [100]:
from math import log, pi
from numpy import asarray

In [101]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [102]:
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([3, 1, 4, 5, 3, 1, 5, 4, 1, 1])

In [103]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [104]:
rolls.mean()

2.8

In [105]:
rolls.tolist()

[3, 1, 4, 5, 3, 1, 5, 4, 1, 1]

In [106]:
rolls + 10

array([13, 11, 14, 15, 13, 11, 15, 14, 11, 11])

In [107]:
rolls <= 3

array([ True,  True, False, False,  True,  True, False, False,  True,
        True])

In [108]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]
