### **Introduction to NumPy:**

NumPy is a powerful library that provides support for arrays, matrices, and mathematical functions, making it a core tool in scientific computing and data analysis. 

Here's an outline of what is contained in NumPy class:

NumPy is a fundamental library in Python for numerical computations and data manipulation. It provides support for arrays and matrices, along with a wide range of mathematical functions to operate on these arrays efficiently. This makes it an essential tool for scientific computing and data analysis tasks.

### **NumPy arrays and Python lists are both used to store collections of data, but they have several key differences in terms of performance, functionality, and memory management. Here's a breakdown of the technical differences between the two:**

**Homogeneity:**

---------------------

NumPy arrays are homogeneous, meaning all elements in the array must be of the same data type (integers, floats, etc.).

Python List: Python lists can store elements of different data types in the same list.

**Performance:**

---------------------

NumPy arrays are optimized for numerical operations. They are more memory-efficient and faster for large-scale numerical computations due to their efficient memory layout and use of low-level operations.

Python List: Python lists are not as optimized for numerical computations and can be slower for large datasets or mathematical operations.

**Memory Efficiency:**

---------------------

NumPy Array: NumPy arrays use a contiguous block of memory, which reduces memory overhead and allows for better cache utilization. This results in better memory efficiency compared to Python lists.

Python List: Python lists are less memory-efficient since they store additional information for each element, including the type and reference count.

**Functionality:**

----------------------

NumPy Array: NumPy arrays offer a wide range of mathematical and array-specific functions for efficient element-wise operations, broadcasting, and advanced array manipulation.

Python List: Python lists offer basic operations like appending, extending, and indexing, but lack the advanced array-specific functionality of NumPy arrays.

**Vectorized Operations:**

-----------------------

NumPy Array: NumPy arrays allow for vectorized operations, where operations are applied element-wise without explicit loops. This leads to cleaner and more concise code.

Python List: Python lists require explicit loops to perform element-wise operations, which can be slower and less readable.


**Size and Shape:**

-----------------------

NumPy Array: NumPy arrays have a fixed size and shape upon creation. Changing the shape requires creating a new array or using specialized functions.

Python List: Python lists can dynamically change in size by appending or removing elements.

**Supported Functions:**

-----------------------


NumPy Array: NumPy arrays support a wide range of mathematical and statistical functions, linear algebra operations, and more, making it suitable for scientific computing and data analysis.

Python List: Python lists lack built-in support for many of the advanced numerical and array operations provided by NumPy.

#### In summary, NumPy arrays are designed specifically for numerical and scientific computing tasks, offering better performance, memory efficiency, and a comprehensive set of functions for working with arrays. Python lists are more general-purpose and flexible but lack the specialized features and optimizations of NumPy arrays when it comes to numerical operations.

### **Diffrence between Numpy and List in code**

In [1]:
# Adding 2 to a Python list
python_list = [1, 3, 5, 7, 9]
python_list_with_2 = [x + 2 for x in python_list]
print("Python List with 2 added:", python_list_with_2)

# Adding 2 to a NumPy array
import numpy as np

numpy_array = np.array([1, 3, 5, 7, 9])
numpy_array_with_2 = numpy_array + 2
print("NumPy Array with 2 added:", numpy_array_with_2)


Python List with 2 added: [3, 5, 7, 9, 11]
NumPy Array with 2 added: [ 3  5  7  9 11]


In [2]:
for x in python_list:
    x + 2
print("Python List with 2 added:", python_list_with_2)
     

Python List with 2 added: [3, 5, 7, 9, 11]


In [3]:
aa = list(map(lambda x:x+2,python_list))
aa

[3, 5, 7, 9, 11]

**Perfomence**

In [4]:
import time
# Create large arrays
python_list = list(range(10**6))
numpy_array = np.array(range(10**6))

# Measure the time taken for element-wise addition using Python list
start_time = time.time()
python_list_sum = [x + 2 for x in python_list]
end_time = time.time()
print(f"Time taken for Python list addition: {end_time - start_time} seconds")

# Measure the time taken for element-wise addition using NumPy array
start_time = time.time()
numpy_array_sum = numpy_array + 2
end_time = time.time()
print(f"Time taken for NumPy array addition: {end_time - start_time} seconds")

Time taken for Python list addition: 0.578507661819458 seconds
Time taken for NumPy array addition: 0.007804155349731445 seconds


**Memory**

In [5]:
import sys

# Create a Python list and a NumPy array with the same data
python_list = list(range(10**6))
numpy_array = np.array(range(10**6))

# Check the size of each object in bytes
size_python_list = sys.getsizeof(python_list)
size_numpy_array = numpy_array.nbytes

print(f"Size of Python list: {size_python_list} bytes")
print(f"Size of NumPy array: {size_numpy_array} bytes")

Size of Python list: 8000056 bytes
Size of NumPy array: 8000000 bytes


### **Installing and Importing NumPy:**

In [6]:
# pip install numpy

In [7]:
#To import NumPy in your Python script or notebook:
import numpy as np

<h3><b>NumPy arange vs linspace</b></h3>

<table>
    <tr>
      <th>Feature</th>
      <th><code>np.arange</code></th>
      <th><code>np.linspace</code></th>
    </tr>
    <tr>
      <td>Syntax</td>
      <td><code>numpy.arange([start, ]stop, [step, ]dtype=None)</code></td>
      <td><code>numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)</code></td>
    </tr>
    <tr>
      <td>Start Value</td>
      <td>Specifies the starting value of the sequence.</td>
      <td>Specifies the starting value of the sequence.</td>
    </tr>
    <tr>
      <td>Stop Value</td>
      <td>Specifies the end value, and the sequence will stop before reaching it.</td>
      <td>Specifies the end value, and the sequence may include it depending on <code>endpoint</code>.</td>
    </tr>
    <tr>
      <td>Spacing</td>
      <td>Specifies the spacing between values.</td>
      <td>Specifies the number of evenly spaced samples to generate.</td>
    </tr>
    <tr>
      <td>Endpoint</td>
      <td>By default, the <code>stop</code> value is not included in the array.</td>
      <td>Determines whether the <code>stop</code> value is included in the array.</td>
    </tr>
    <tr>
      <td>Number of Samples (<code>num</code>)</td>
      <td>Not applicable.</td>
      <td>Specifies the number of evenly spaced samples to generate.</td>
    </tr>
    <tr>
      <td>Return Step Size (<code>retstep</code>)</td>
      <td>Not applicable.</td>
      <td>If <code>True</code>, returns the step size between values.</td>
    </tr>
    <tr>
      <td>Data Type (<code>dtype</code>)</td>
      <td>Sets the data type of the output array.</td>
      <td>Sets the data type of the output array.</td>
    </tr>
  </table>

In [8]:
arr1 = np.arange(0, 10, 2, dtype='int') 
arr1

array([0, 2, 4, 6, 8])

In [9]:
arr2 = np.linspace(0, 10, num=4, dtype='int', endpoint=False)  # Creates array: [ 0.,  2.5,  5.,  7.5, 10.]
arr2

array([0, 2, 5, 7])

In [10]:
t = np.linspace(0,20, 10, endpoint=False, dtype='int')
t

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### **Types of the Numpy Array**

#### **Numpy 1D Array**
##### **NumPy – Create 1D Array**

- One dimensional array contains elements only in one dimension. In other words, the shape of the numpy array should contain only one value in the tuple.
- To create a one dimensional array in numpy, you can use either of the numpy.array(), numpy.arange(), or numpy.linspace() functions based on the choice of initialisation.

**Create 1D NumPy Array using array() function**

- Numpy array() functions takes a list of elements as argument and returns a one-dimensional array.
- In this example, we will import numpy library and use array() function to crate a one dimensional numpy array.

In [11]:
arr3 = np.array([5, 8, 12])
print(arr3)

[ 5  8 12]


In [12]:
arr3.shape

(3,)

**Create 1D NumPy Array using arange() function**

- NumPy arange() function takes start, end of a range and the interval as arguments and returns a one-dimensional array.
- `[start, start+interval, start+2*interval, ... ]`
- In this example, we will import numpy library and use arange() function to crate a one dimensional numpy array.

In [13]:
arr4 = np.arange(5, 14, 2)

print(arr4)

[ 5  7  9 11 13]


##### **NumPy 2D Array**

To create a 2D (2 dimensional) array in Python using NumPy library, we can use any of the following methods.

- `numpy.array()` – Creates array from given values.
- `numpy.zeros()` – Creates array of zeros.
- `numpy.ones()` – Creates array of ones.
- `numpy.empty()` – Creates an empty array.

**Create 2D Array using `numpy.array()`**

In [14]:
# create a 2D array with shape (3, 4)
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
arr5.shape

(3, 4)

**Create 2D Array using numpy.zeros()**

- Pass shape of the required 2D array, as a tuple, as argument to `numpy.zeros()` function. The function returns a numpy array with specified shape, and all elements in the array initialised to zeros.

In [16]:
# create a 2D array with shape (3, 4)
arr6 = np.zeros((3,4), dtype=int)
print(arr6)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
# create a 2D array with shape (3, 4)
shape = (3, 4)
arr7 = np.ones(shape, dtype='int')
print(arr7)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
# create a 2D array with shape (3, 4)
arr8 = np.empty((3,4), dtype=int)
print(arr8)

[[      1658824839512                  50                   0
                    0]
 [  29555310641283072 4120349891991070059 3257898278702178916
  4049919334472167987]
 [3471539959309544801 3486739818625459504 8386112019185558881
  7003995932826432373]]


#### **Numpy 3D Array**

To create a 3D (3 dimensional) array in Python using NumPy library, we can use any of the following methods.

- `numpy.array()` – Creates array from given values.
- `numpy.zeros()` – Creates array of zeros.
- `numpy.ones()` – Creates array of ones.
- `numpy.empty()` – Creates an empty array.

**Create 3D Array using `numpy.array()`**

- Pass a nested list (list of lists of lists) to numpy.array() function.
- In the following program, we create a numpy 3D array of shape (2, 3, 4).

In [19]:
# create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],

[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

arr9 = np.array(nested_list)

print(arr9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [20]:
arr9.shape

(2, 3, 4)

In [21]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 3, 4)

arr11 = np.zeros(shape, dtype='int')

print(arr11)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [22]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 2, 4)

arr12 = np.ones(shape, dtype='int')

print(arr12)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [23]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 3, 4)

arr13 = np.empty(shape, dtype='int')

print(arr13)

[[[      1658752777336                 149                   0
                     0]
  [       197568495616 4189022085447885435 7018141364393288224
   2325039521791501684]
  [7599578601909023329 7309449296458311796 2318284121462417440
   8097868449970923828]]

 [[2318283056109920357 6660362230965480498 4404575623523230062
   8315173710809034272]
  [2318339441533940520 7577092403962147940 7952352384135951470
   8241913273598440048]
  [2459013921775956338 8028075858292209765 2482730745246998382
     12948386641748026]]]


### **numpy.random module:**
- This module provides a suite of functions for generating random numbers.

#### **numpy.random.rand:**
- This function generates random numbers from a uniform distribution over [0, 1]. It takes dimensions as input and returns an array of the specified shape.

In [24]:
random_numbers = np.random.rand(3,3)  # Generates a 2x3 array of random numbers between 0 and 1
random_numbers

array([[0.89176629, 0.16368145, 0.72977825],
       [0.93689793, 0.68607103, 0.85963801],
       [0.67168018, 0.32848478, 0.94431972]])

#### **numpy.random.randn:**
- This function generates random numbers from a standard normal distribution `(mean=0, standard deviation=1)`. It also takes dimensions as input and returns an array of the specified shape.

In [25]:
random_numbers = np.random.randn(2, 3)  # Generates a 2x3 array of random numbers from a standard normal distribution
random_numbers

array([[-1.43269864, -0.25508748,  1.47564333],
       [ 1.67208133, -0.11761722, -1.14975788]])

#### **numpy.random.randint:**
- This function generates random integers from a specified low (inclusive) to high (exclusive) range. It can take additional parameters to specify the size and shape of the output array.

In [26]:
random_integers = np.random.randint(-10, 10, size=(2, 3))  # Generates a 2x3 array of random integers between 1 (inclusive) and 10 (exclusive)
random_integers

array([[ 8,  3,  4],
       [ 2,  5, -6]], dtype=int32)

### **Creating Numpy array**

In [27]:
ac = np.array([2,4,56,422,32,1])
ac

array([  2,   4,  56, 422,  32,   1])

In [28]:
#to find the type
type(ac)

numpy.ndarray

In [29]:
np.arange(2, 10, dtype=int)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
i = np.identity(2) #indentity matrix is that diagonal items will be ones and evrything will be zeros
i

array([[1., 0.],
       [0., 1.]])

In [31]:
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [32]:
x = np.array([1,2,3])
y = x 
z = np.copy(x)
print(x,y,z)


[1 2 3] [1 2 3] [1 2 3]


In [33]:
np.linspace(2.0, 3.0 ,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [34]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

#### **Changing the type of the data type**

In [35]:
ad = np.array([11,23,44], dtype = float)
ad

array([11., 23., 44.])

In [36]:
ad.astype('int')

array([11, 23, 44])

In [37]:
i = np.linspace(2,10,num=8, dtype=float)
i.astype(int)

array([ 2,  3,  4,  5,  6,  7,  8, 10])

#### **Reshape**
- Both of number products should be equal to umber of Items present inside the array.

In [38]:
re = np.arange(1,11)
re.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
re = np.arange(1,11).reshape(5,2)
re1 = np.arange(1,11).reshape(2,5)
re2 = np.arange(1,13).reshape(3,4)
re2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### **Shape**
- gives each item consist of no.of rows and np.of column

In [40]:
re = np.arange(1,11).reshape(5,2)
re.shape
re1.shape

(2, 5)

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5,6,4]])
reshaped_arr = np.reshape(arr, (3, 2))
finding_shape=reshaped_arr.shape
reshaped_arr,finding_shape

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

#### **Size**
- gives number of items

In [42]:
re = np.arange(1,11).reshape(5,2)
re.size

10

In [43]:
re2.size

12

In [44]:
len(re2)

3

#### **ItemSize**
- Memory occupied by the item

In [45]:
re2 = np.arange(1,13).reshape(3,4)
print(re2)
re2.itemsize #Memory occupied by the item

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


8

In [46]:
re3 = np.linspace(0,10, num=10)
re3.itemsize

8

### **Array Operations:**
- NumPy supports element-wise operations on arrays. Basic arithmetic operations like addition, subtraction, multiplication, and division are performed element-wise.

#### **Scalr Operation**
- Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array.

In [47]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [48]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
z1 + 2 # -, *, /, **, %.

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [50]:
arr1d = np.array([1,2,3,4,5])
re_add = arr1d + 2
re_add1 = arr1d * 2
re_add2 = arr1d - 2
re_add, re_add1, re_add2

(array([3, 4, 5, 6, 7]),
 array([ 2,  4,  6,  8, 10]),
 array([-1,  0,  1,  2,  3]))

#### **Relational Operation**
- The relational operators are also known as comparison operators, their main function is to return either a true or false based on the value of operands.

In [51]:
z2 = np.arange(12,24).reshape(3,4)
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
z2[z2 > 20]

array([21, 22, 23])

In [53]:
ar1 = np.array([[-1,2,7]])
ar2 = np.array([[4,5,6]])

comp = ar1>ar2
comp

array([[False, False,  True]])

In [54]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([True, True,False, False])

_and = np.logical_and(arr1,arr2)

_or = np.logical_or(arr1,arr2)
_and,_or

(array([ True, False, False, False]), array([ True,  True,  True, False]))

In [55]:
arr1 = np.array([1, 3, 7])
arr2 = np.array([2, 3, 6])

# Logical AND where both conditions are True (e.g., arr1 > 2 and arr2 > 2)
result_and = np.logical_and(arr1 > 2, arr2 > 2)
print(result_and)

# Logical OR where either condition is True (e.g., arr1 > 2 or arr2 > 2)
result_or = np.logical_or(arr1 > 2, arr2 > 2)
print(result_or)

[False  True  True]
[False  True  True]


#### **Vector Operation**
- We can apply on both numpy array

In [56]:
arr1 = np.array([1, 2, 3]) + 5
arr2 = np.array([4, 5, 6])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print(arr1)
print(addition,subtraction, multiplication, division)

[6 7 8]
[10 12 14] [2 2 2] [24 35 48] [1.5        1.4        1.33333333]


In [57]:
za = np.arange(12).reshape(3,4)
zb = np.arange(12, 24).reshape(3,4)
za, zb

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [58]:
addition = za + zb
subtraction = za - zb
multiplication = za * zb
print("Addition:\n", addition, "\n")

Addition:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 



### **Array Function**

In [59]:
k1 = np.random.random((3,3))
k1

array([[0.70772931, 0.21015297, 0.62466002],
       [0.86745319, 0.53489336, 0.88561379],
       [0.37768619, 0.29299884, 0.04630017]])

In [60]:
k2 = np.round(k1*100)
k2.astype('int')

array([[71, 21, 62],
       [87, 53, 89],
       [38, 29,  5]])

In [61]:
aa1 = np.sum(k2, axis=1) #axis=1 represents rows , 0-columns
aa1

array([154., 229.,  72.])

In [62]:
a1 = np.max(k2)

# if we want maximum of every row
a11 = np.max(k2, axis=1)

# # maximum of every column
a22 = np.min(k2, axis=0)

a2 = np.min(k2)
a3 = np.sum(k2)
a4 = np.prod(k2) #Multiplication


a1, a11, a22, a2, a3, a4

(np.float64(89.0),
 array([71., 89., 38.]),
 array([38., 21.,  5.]),
 np.float64(5.0),
 np.float64(455.0),
 np.float64(209028767904180.0))

### **Statistics Function**

In [63]:
k2

array([[71., 21., 62.],
       [87., 53., 89.],
       [38., 29.,  5.]])

In [64]:
avg = np.sum(k2)/np.size(k2)
np.round(avg, 2)

np.float64(50.56)

In [65]:
b1 = np.mean(k2)

# mean of every column
b11 = k2.mean(axis=0)

b2 = np.median(k2)

#median of every row
b22 = np.median(k2, axis=1)

b3 = np.var(k2)

b4 = np.std(k2)

b1, b11, b2, b22, b3, b4

(np.float64(50.55555555555556),
 array([65.33333333, 34.33333333, 52.        ]),
 np.float64(53.0),
 array([62., 87., 29.]),
 np.float64(770.246913580247),
 np.float64(27.753322568302465))

#### **Trignometric Finction**

In [66]:
s2 = np.arange(24, 36).reshape(3,4)
s3 = np.arange(36,48).reshape(4,3)
s2

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [67]:
np.sin(s2)

array([[-0.90557836, -0.13235175,  0.76255845,  0.95637593],
       [ 0.27090579, -0.66363388, -0.98803162, -0.40403765],
       [ 0.55142668,  0.99991186,  0.52908269, -0.42818267]])

In [68]:
np.cos(s2)

array([[ 0.42417901,  0.99120281,  0.64691932, -0.29213881],
       [-0.96260587, -0.74805753,  0.15425145,  0.91474236],
       [ 0.83422336, -0.01327675, -0.84857027, -0.90369221]])

In [69]:
np.tan(s2)

array([[ -2.1348967 ,  -0.13352641,   1.17875355,  -3.2737038 ],
       [ -0.2814296 ,   0.88714284,  -6.4053312 ,  -0.44169557],
       [  0.66100604, -75.3130148 ,  -0.62349896,   0.47381472]])

In [70]:
a = np.sin(180)
b = np.cos(45)
c= np.tan(45)

sec = 1/a
cosec = 1/b
cot = 1/np.tan(45)

a

np.float64(-0.8011526357338304)

#### **Log and Exponent**

In [71]:
np.log(100)

np.float64(4.605170185988092)

In [72]:
np.exp(10)

np.float64(22026.465794806718)

In [73]:
np.sqrt(25)

np.float64(5.0)

In [74]:
np.power(2,3)

np.int64(8)

In [75]:
arr4 = np.array([10, 20, 30, 40, 50])
sqrt_result = np.sqrt(arr4)
print(sqrt_result)

exp_result = np.exp(arr4)

#trignometry
sin_result = np.sin(arr4)
cos_result = np.cos(arr4)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


#### **round**
The `numpy.round()` function rounds the elements of an array to the nearest integer or to the specified number of decimals.

In [76]:
# Round to the nearest integer
arr = np.array([1.2, 2.7, 3.5, 4.9])
rounded_arr = np.round(arr)
print(rounded_arr) 

[1. 3. 4. 5.]


In [77]:
# Round to two decimals
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


#### **Floor**
The `numpy.floor()` function returns the largest integer less than or equal to each element of an array.


In [78]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [189]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[70., 19., 73.],
       [32., 44., 57.]])

#### **Ceil**
The `numpy.ceil()` function returns the smallest integer greater than or equal to each element of an array.


In [80]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [81]:
np.ceil(np.random.random((2,3))*100) # gives highest integer

array([[98., 11., 55.],
       [70., 48., 57.]])

### **Set functions**
- `np.union1d`
- `np.intersect1d`
- `np.setdiff1d`

In [82]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [83]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [84]:
np.intersect1d(m,n)

array([3, 4, 5])

In [190]:
# Set difference
np.setdiff1d(n,m)

array([6, 7])

### **Indexing and Slicing:**
You can access and modify elements of arrays using indexing and slicing. Indexing starts at 0, and slicing allows you to extract portions of arrays.

In [191]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
first_element = arr[0]
sub_array = arr[1:4]
a = arr[-1]
first_element,sub_array,a

(np.int64(10), array([20, 30, 40]), np.int64(50))

In [192]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [193]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
p2[1,2]

np.int64(6)

In [194]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [91]:
# :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 5 is in second matrix which is 1 .and 1 row so 0 and second column so 1
p3[1,0,1]

#Here first we take 0 because our desired is 0, is in first matrix which is 0 . and 1 row so 0 and first column so 0
p3[1,1,0]

np.int64(6)

In [92]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
p1[2:5]

array([2, 3, 4])

In [94]:
p1[2:5:2]

array([2, 4])

In [95]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
p2[0:1,1:]

array([[1, 2, 3]])

In [97]:
# fetching total First row
p2[0, :]

array([0, 1, 2, 3])

In [98]:
# fetching total third column
p2[:,2]

array([ 2,  6, 10])

In [99]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [195]:
#3D Slicing
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [101]:
p3[0,1,:] 

array([2, 3])

In [102]:
p3[1,:,1]

array([5, 7])

#### **Isin**
- we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [103]:
a = np.array([10,20,30,110])
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)


array([ True,  True,  True, False])

In [104]:
a[np.isin(a,items)]

array([10, 20, 30])

In [105]:
np.isin(10, items)

array(True)

In [106]:
# Create a 2D array
arr = np.array([[1, 3, 5],
                [8, 2, 4]])

# Find the index of the maximum value in the entire array
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)

# Find the indices of the maximum values along each column
max_indices_col = np.argmax(arr, axis=0)
print("Indices of maximum values along each column:", max_indices_col)

Index of maximum value: 3
Indices of maximum values along each column: [1 0 0]


In [107]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 3, 5],
                [8, 2, 4]])

# Find the index of the minimum value in the entire array
min_index = np.argmin(arr)
print("Index of minimum value:", min_index)

# Find the indices of the minimum values along each row
min_indices_row = np.argmin(arr, axis=1)
print("Indices of minimum values along each row:", min_indices_row)

Index of minimum value: 0
Indices of minimum values along each row: [0 1]


### **Array Methods**

#### **`np.where`**
The numpy.where() function returns the indices of elements in an input array where the given
condition is satisfied.

In [108]:
a = np.arange(1,101)
print(a)
np.where(a>50)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [109]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

#### **Itrating**

In [110]:
p1 = np.arange(10)

for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [111]:
p2 = np.arange(12).reshape(3,4)

## Looping on 2D array
for i in p2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [112]:
p3 = np.arange(8).reshape(2,2,2)

## Looping on 2D array
for i in p3:
    print(i) 

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [113]:
for i in p3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


print all items in 2D & 3D using nditer ----> first convert in to 1D and applying Loop

In [114]:
for i in np.nditer(p2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [115]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7


In [116]:
p4 = np.arange(12,24).reshape(3,4)
p4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [117]:
for i in np.nditer(p4):
    if i % 2 == 0:
        print(i)

12
14
16
18
20
22


#### **Sorting**

In [118]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
a , b

(array([11, 20, 76, 62, 94, 41, 59,  4, 62, 94, 30, 60, 78, 47, 60],
       dtype=int32),
 array([[79, 19, 45, 29],
        [24, 50, 63, 48],
        [34, 10, 45, 56],
        [39, 56, 14, 54],
        [87, 25, 63, 92],
        [83, 38, 95, 16]], dtype=int32))

In [119]:
np.sort(a)

array([ 4, 11, 20, 30, 41, 47, 59, 60, 60, 62, 62, 76, 78, 94, 94],
      dtype=int32)

In [120]:
np.sort(a)[::-1] #Descending

array([94, 94, 78, 76, 62, 62, 60, 60, 59, 47, 41, 30, 20, 11,  4],
      dtype=int32)

In [121]:
np.sort(b)

array([[19, 29, 45, 79],
       [24, 48, 50, 63],
       [10, 34, 45, 56],
       [14, 39, 54, 56],
       [25, 63, 87, 92],
       [16, 38, 83, 95]], dtype=int32)

In [122]:
np.sort(b, axis=0) #Column wise sorting

array([[24, 10, 14, 16],
       [34, 19, 45, 29],
       [39, 25, 45, 48],
       [79, 38, 63, 54],
       [83, 50, 63, 56],
       [87, 56, 95, 92]], dtype=int32)

#### **Append**

In [123]:
np.append(b,1)

array([79, 19, 45, 29, 24, 50, 63, 48, 34, 10, 45, 56, 39, 56, 14, 54, 87,
       25, 63, 92, 83, 38, 95, 16,  1])

In [124]:
b

array([[79, 19, 45, 29],
       [24, 50, 63, 48],
       [34, 10, 45, 56],
       [39, 56, 14, 54],
       [87, 25, 63, 92],
       [83, 38, 95, 16]], dtype=int32)

In [125]:
b.shape[1]

4

In [126]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [127]:
# adding one row to 2d arrary
np.append(b,np.ones((6,1))).astype('int')

array([79, 19, 45, 29, 24, 50, 63, 48, 34, 10, 45, 56, 39, 56, 14, 54, 87,
       25, 63, 92, 83, 38, 95, 16,  1,  1,  1,  1,  1,  1])

In [128]:
# add new column
np.append(b,np.random.random((6,1)),axis=1)

array([[7.90000000e+01, 1.90000000e+01, 4.50000000e+01, 2.90000000e+01,
        2.96770586e-01],
       [2.40000000e+01, 5.00000000e+01, 6.30000000e+01, 4.80000000e+01,
        2.79272757e-02],
       [3.40000000e+01, 1.00000000e+01, 4.50000000e+01, 5.60000000e+01,
        3.76747381e-01],
       [3.90000000e+01, 5.60000000e+01, 1.40000000e+01, 5.40000000e+01,
        2.04983464e-01],
       [8.70000000e+01, 2.50000000e+01, 6.30000000e+01, 9.20000000e+01,
        6.17479172e-01],
       [8.30000000e+01, 3.80000000e+01, 9.50000000e+01, 1.60000000e+01,
        6.82450573e-01]])

#### **`np.unique`**

In [129]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [130]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### **Dot Product**
`np.dot`

In [131]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [132]:
c = np.dot(a,b)
c

array([[19, 22],
       [43, 50]])

In [133]:
A = np.array([[11, 12], [13, 14]])
B = np.array([[15, 16], [17, 18]])
dot_product = np.dot(A, B)
dot_product

array([[369, 392],
       [433, 460]])

#### **Percentaile**
- `numpy.percentile()` function used to compute the nth percentile of the given data (array elements) along the specified axis

In [134]:
import numpy as np

In [135]:
a = np.random.randint(1,100,16)
b = np.random.randint(1,100,24).reshape(6,4)

In [136]:
np.sort(a)

array([21, 28, 32, 37, 40, 43, 50, 52, 52, 56, 60, 80, 83, 87, 98, 99],
      dtype=int32)

In [137]:
np.percentile(a,100) #max

np.float64(99.0)

In [138]:
np.percentile(a,0) # min

np.float64(21.0)

In [139]:
np.percentile(a,50) #median

np.float64(52.0)

In [140]:
np.percentile(a,25) 

np.float64(39.25)

In [141]:
np.percentile(a,75) 

np.float64(80.75)

#### **Flip**
- The `numpy.flip()` function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [142]:
a

array([56, 60, 99, 50, 80, 40, 98, 52, 83, 32, 28, 52, 21, 43, 37, 87],
      dtype=int32)

In [143]:
np.flip(a)

array([87, 37, 43, 21, 52, 28, 32, 83, 52, 98, 40, 80, 50, 99, 60, 56],
      dtype=int32)

In [144]:
b

array([[62, 30, 74, 77],
       [24, 82, 39,  9],
       [93, 56, 32, 60],
       [36, 23, 78, 96],
       [23, 17,  2, 59],
       [26, 11, 32, 73]], dtype=int32)

In [145]:
np.flip(b,axis=0)

array([[26, 11, 32, 73],
       [23, 17,  2, 59],
       [36, 23, 78, 96],
       [93, 56, 32, 60],
       [24, 82, 39,  9],
       [62, 30, 74, 77]], dtype=int32)

#### **Delete**
The `numpy.delete()` function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [146]:
a = np.random.randint(1,100,15)
a

array([44,  9, 74, 51, 45, 99,  6, 62, 85, 74,  4, 89, 36, 85, 43],
      dtype=int32)

In [147]:
np.delete(a,0)

array([ 9, 74, 51, 45, 99,  6, 62, 85, 74,  4, 89, 36, 85, 43],
      dtype=int32)

In [148]:
np.delete(a,[0,2,4]) # deleted 0,2,4 index items

array([ 9, 51, 99,  6, 62, 85, 74,  4, 89, 36, 85, 43], dtype=int32)

In [149]:
b

array([[62, 30, 74, 77],
       [24, 82, 39,  9],
       [93, 56, 32, 60],
       [36, 23, 78, 96],
       [23, 17,  2, 59],
       [26, 11, 32, 73]], dtype=int32)

In [150]:
np.delete(b, [0,4])

array([30, 74, 77, 82, 39,  9, 93, 56, 32, 60, 36, 23, 78, 96, 23, 17,  2,
       59, 26, 11, 32, 73], dtype=int32)

### **Array Manipulation:**
You can reshape arrays using `np.reshape()`, flatten them using `np.flatten()` or `np.ravel()`, and transpose them using `np.transpose()` or array attributes.

Transpose ---> Converts rows in to clumns ad columns into rows

In [151]:
p2 = np.arange(12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [153]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [154]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
arr,transposed_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

#### **Ravel**
Converting any dimensions to 1D

In [155]:
p2 = np.arange(12).reshape(3,4)
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [157]:
p3 = np.arange(0,8).reshape(2,2,2)
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [158]:
np.ravel(p3)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [159]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [160]:
p2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [161]:
p3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

#### **Inverse of Array**

In [162]:
#To invert (or find the inverse of) a NumPy array, you can use the numpy.linalg.inv()
import numpy as np

# Create a square matrix (2x2 for example)
matrix = np.array([[4, 7],
                   [2, 6]])

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix)

# Print the original and inverse matrices
print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


#### **Array Concatenation** 
You can combine arrays using functions like `np.concatenate()`, `np.vstack()`, and `np.hstack()`.

In [163]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5,6,4],[5,6,1]])
print(arr)
print(arr2)
concate = np.concatenate((arr,arr2),axis=0)
concate

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 4],
       [5, 6, 1]])

#### **Stacking**
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked

In [164]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack = np.vstack((arr1, arr2))
horizantal_stack = np.hstack((arr1, arr2))
vertical_stack,horizantal_stack
# assingment : create an example for -> hstack, spilt, vsplit &hsplit

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [165]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)
print(w1)
print(w2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [166]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [167]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### **Splitting:**
- its opposite of Stacking
- Splitting arrays can be done with `np.split()`, `np.vsplit()`, and `np.hsplit()`.

In [168]:
arr1 = np.array([1,2,3,4,5,6])
splitting = np.split(arr1, 3)
splitting

[array([1, 2]), array([3, 4]), array([5, 6])]

In [169]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [170]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [171]:
a = np.array([[1,3,6],[5,8,9],[5,5,6]])
a

array([[1, 3, 6],
       [5, 8, 9],
       [5, 5, 6]])

In [172]:
np.hsplit(a,3)

[array([[1],
        [5],
        [5]]),
 array([[3],
        [8],
        [5]]),
 array([[6],
        [9],
        [6]])]

In [173]:
np.vsplit(a,3)

[array([[1, 3, 6]]), array([[5, 8, 9]]), array([[5, 5, 6]])]

### **Boolean Indexing and Fancy Indexing:**
It allows you to select elements from an array based on a Boolean condition. This allows you to extract only the elements of an array that meet a certain condition, making it easy to perform operations on specific subsets of data.

In [174]:
arr = np.array([10, 20, 30, 40, 50])
bool_idx = arr > 25
print(bool_idx)
selected_elements = arr[bool_idx]

indices = np.array([0, 2, 4])
fancy_selected = arr[indices]

selected_elements,fancy_selected


[False False  True  True  True]


(array([30, 40, 50]), array([10, 30, 50]))

In [175]:
G = np.random.randint(1,100,24).reshape(6,4)
G

array([[49,  1, 13, 95],
       [24, 31,  7, 60],
       [67, 46, 35, 67],
       [58, 41, 44, 68],
       [42, 95, 44, 50],
       [97, 95,  4, 46]], dtype=int32)

In [176]:
G > 50

array([[False, False, False,  True],
       [False, False, False,  True],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [False,  True, False, False],
       [ True,  True, False, False]])

In [177]:
# Where is True , it gives result , everything other that removed.
G[G > 50]

array([95, 60, 67, 67, 58, 68, 95, 97, 95], dtype=int32)

In [178]:
G % 2 == 0

array([[False, False, False, False],
       [ True, False, False,  True],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [179]:
# find out even numbers
G[G % 2 == 0]

array([24, 60, 46, 58, 44, 68, 42, 44, 50,  4, 46], dtype=int32)

In [180]:
# find all numbers greater than 50 and are even
G[(G > 50 ) & (G % 2 == 0)] 

array([60, 58, 68], dtype=int32)

In [181]:
# Result
G[~(G % 7 == 0)] # (~) = Not

array([ 1, 13, 95, 24, 31, 60, 67, 46, 67, 58, 41, 44, 68, 95, 44, 50, 97,
       95,  4, 46], dtype=int32)

In [182]:
G

array([[49,  1, 13, 95],
       [24, 31,  7, 60],
       [67, 46, 35, 67],
       [58, 41, 44, 68],
       [42, 95, 44, 50],
       [97, 95,  4, 46]], dtype=int32)

In [183]:
G[np.array([0, 2, 4])]

array([[49,  1, 13, 95],
       [67, 46, 35, 67],
       [42, 95, 44, 50]], dtype=int32)

### **Array Broadcasting:**
Broadcasting allows you to perform operations between arrays of different shapes. 

NumPy automatically handles shape compatibility by replicating values along dimensions as needed. This is particularly useful for operations that involve arrays of different shapes.

In [184]:
# Scalar and Array Broadcasting
scalar = 5
array = np.array([1, 2, 3, 4, 5])
result_scalar_array = scalar * array
result_scalar_array

array([ 5, 10, 15, 20, 25])

In [185]:
# Arrays of Different Shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result_broadcasting = arr1 * arr2
arr1.shape,arr2.shape,result_broadcasting

((2, 3),
 (3,),
 array([[ 10,  40,  90],
        [ 40, 100, 180]]))

### **File I/O with NumPy:**
You can save and load arrays to/from files using np.save() and np.load(). For instance:

In [186]:
arr = np.array([[1, 2, 3],[4,5,6]])
np.save('my_array.npy', arr)

In [187]:
loaded_arr = np.load('my_array.npy')
loaded_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [188]:
loaded_arr[loaded_arr %2==0]

array([2, 4, 6])